id: I42CE82E9
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:13:55.873175'
last_modified: '2022-06-18T20:13:55.873188'
parser: null
source_metadata:
  title: Reply to criticisms of the Kālacakra (Old block print), colophon excerpt
  author: gos lo tsA ba gzhon nu dpal/
  description: 'Digital version 1.0 {Wylie}, diplomatic edition of witness A; WYLIE
    COPY of master xml (completed: 2020-05-26); revised, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:-
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/2120
  bases:
    06db:
      title: Reply to criticisms of the Kālacakra (Old block print), colophon excerpt
      order: 1
      base_file: 06db.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
